# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2a40b8958f11611968c1d468425aca88e18af9ba0bb8d7838d8fe6627a249ea161bc7eeefab22efd1c4e894f0f3af14e56538bf38e8731c5c0bd14d82b591e

test:
  secret_key_base: 24ee5ed66a2e4c86400bf398b90ed2d7d0ca6092c14b0cf521b6fede58c7146d11570a25abdc69285861bb028088b230aae23fd1276b16fb7b9da813fd802e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
